### ISSUE TITLE
run_finetuning_Nemo-full.py: freezing while downloading models?

### ISSUE THREAD

**Issue by SimonOuellette35** [da-fr/arc-prize-2024#2]
I'm trying to fine-tune on a RunPod instance with your script run_finetuning_Nemo-full.py. The script starts, and then freezes systematically at:

model-00003-of-00004.safetensors:  45%|█████████████████████████████████████████████████████████████▊                                                                          | 2.23G/4.92G

I stopped everything, ran it again, and it froze at exactly the same place. Have you seen this before? When I say "it froze", I gave up after about 45 minutes.

Any thoughts on what could cause this?

**Comment by da-fr** [comment]
I have never seen the download freeze before. Reasons for this could be low disk space, or an unstable internet connection.
If the problem persists, you could try to download the model via git. To do this, open the model on huggingface.co, click on the three dots, and then on "clone repository".
